export const steps = [
  {
    label: "Vehicle Model",
    name: "Vehicle_Model",
    type: "select",
    options: ["Truck", "Van", "Bus", "Motorcycle", "Car", "SUV"],
  },
  { label: "Mileage", name: "Mileage", type: "number" },
  {
    label: "Maintenance History",
    name: "Maintenance_History",
    type: "select",
    options: ["Poor", "Good", "Average"],
  },
  { label: "Reported Issues", name: "Reported_Issues", type: "number" },
  { label: "Vehicle Age", name: "Vehicle_Age", type: "number" },
  {
    label: "Fuel Type",
    name: "Fuel_Type",
    type: "select",
    options: ["Electric", "Diesel", "Petrol"],
  },
  {
    label: "Transmission Type",
    name: "Transmission_Type",
    type: "select",
    options: ["Automatic", "Manual"],
  },
  { label: "Engine Size", name: "Engine_Size", type: "number" },
  { label: "Odometer Reading", name: "Odometer_Reading", type: "number" },
  { label: "Last Service Date", name: "Last_Service_Date", type: "date" },
  { label: "Warranty Expiry Date", name: "Warranty_Expiry_Date", type: "date" },
  {
    label: "Owner Type",
    name: "Owner_Type",
    type: "select",
    options: [
      "First",
      "Second",
      "Third",
      "Fourth",
      "Fifth",
      "Sixth",
      "Seventh",
      "Eighth",
      "Ninth",
      "Tenth",
    ],
  },
  { label: "Insurance Premium", name: "Insurance_Premium", type: "number" },
  { label: "Service History", name: "Service_History", type: "number" },
  { label: "Accident History", name: "Accident_History", type: "number" },
  { label: "Fuel Efficiency", name: "Fuel_Efficiency", type: "number" },
  {
    label: "Tire Condition",
    name: "Tire_Condition",
    type: "select",
    options: ["New", "Good", "Worn Out"],
  },
  {
    label: "Brake Condition",
    name: "Brake_Condition",
    type: "select",
    options: ["New", "Good", "Worn Out"],
  },
  {
    label: "Battery Status",
    name: "Battery_Status",
    type: "select",
    options: ["New", "Weak", "Good"],
  },
];
